#!/usr/bin/env python3
"""Register AuraCall project-bound agents as Open Notebook language models.

The expected inputs are AuraCall client handoff env files generated by
`POST /v1/agent-setup-handoffs`. The files are user-scoped runtime state and
must not be committed.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import httpx
from pydantic import SecretStr

from open_notebook.ai.auracall import AURACALL_PROVIDER, DEFAULT_AURACALL_BASE_URL
from open_notebook.ai.models import DefaultModels, Model
from open_notebook.database.repository import repo_query
from open_notebook.domain.credential import Credential


@dataclass(frozen=True)
class AuraCallAgent:
    id: str
    label: str
    client_env_path: Path

    @property
    def model_name(self) -> str:
        return f"agent:{self.id}"

    @property
    def credential_name(self) -> str:
        return f"AuraCall {self.label} - Open Notebook"


DEFAULT_AGENTS = [
    AuraCallAgent(
        id="open-notebook-instant-chatgpt-soylei",
        label="Instant",
        client_env_path=Path("~/.auracall/clients/open-notebook-instant-chatgpt-soylei.env"),
    ),
    AuraCallAgent(
        id="open-notebook-medium-chatgpt-soylei",
        label="Medium",
        client_env_path=Path("~/.auracall/clients/open-notebook-medium-chatgpt-soylei.env"),
    ),
    AuraCallAgent(
        id="open-notebook-pro-chatgpt-soylei",
        label="Pro",
        client_env_path=Path("~/.auracall/clients/open-notebook-pro-chatgpt-soylei.env"),
    ),
]


def _read_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for raw_line in path.expanduser().read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def _agent_config(agent: AuraCallAgent) -> tuple[str, str]:
    override_base_url = os.environ.get("OPEN_NOTEBOOK_AURACALL_BASE_URL")
    path = agent.client_env_path.expanduser()
    if path.exists():
        values = _read_env_file(path)
        base_url = (
            override_base_url
            or values.get("OPENAI_BASE_URL")
            or values.get("AURACALL_BASE_URL")
        )
        api_key = values.get("OPENAI_API_KEY") or values.get("AURACALL_API_KEY")
        if not base_url or not api_key:
            raise ValueError(f"Missing OPENAI_BASE_URL/OPENAI_API_KEY in {path}")
        return base_url.rstrip("/"), api_key

    base_url = override_base_url or os.environ.get(
        "AURACALL_BASE_URL", DEFAULT_AURACALL_BASE_URL
    )
    api_key = os.environ.get(f"OPEN_NOTEBOOK_AURACALL_API_KEY_{agent.label.upper()}") or os.environ.get(
        "OPEN_NOTEBOOK_AURACALL_API_KEY"
    )
    if not api_key:
        raise FileNotFoundError(
            f"{path} does not exist and no OPEN_NOTEBOOK_AURACALL_API_KEY was provided"
        )
    return base_url.rstrip("/"), api_key


async def _reachable(base_url: str, api_key: str, model_name: str) -> bool:
    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            response = await client.get(
                f"{base_url}/models",
                headers={"Authorization": f"Bearer {api_key}"},
            )
            response.raise_for_status()
            models = response.json().get("data", [])
            return any(model.get("id") == model_name for model in models)
    except Exception:
        return False


async def _find_credential(name: str) -> Credential | None:
    rows = await repo_query(
        "SELECT * FROM credential WHERE name = $name AND provider = $provider LIMIT 1",
        {"name": name, "provider": AURACALL_PROVIDER},
    )
    if not rows:
        return None
    return Credential._from_db_row(rows[0])


async def _ensure_credential(agent: AuraCallAgent, base_url: str, api_key: str) -> Credential:
    credential = await _find_credential(agent.credential_name)
    if credential is None:
        credential = Credential(
            name=agent.credential_name,
            provider=AURACALL_PROVIDER,
            modalities=["language"],
            api_key=SecretStr(api_key),
            base_url=base_url,
        )
    else:
        credential.modalities = sorted(set(credential.modalities + ["language"]))
        credential.api_key = SecretStr(api_key)
        credential.base_url = base_url
    await credential.save()
    return credential


async def _find_model(model_name: str) -> Model | None:
    rows = await repo_query(
        """
        SELECT * FROM model
        WHERE provider = $provider
          AND type = 'language'
          AND name = $name
        LIMIT 1
        """,
        {"provider": AURACALL_PROVIDER, "name": model_name},
    )
    if not rows:
        return None
    return Model(**rows[0])


async def _ensure_model(agent: AuraCallAgent, credential: Credential) -> Model:
    model = await _find_model(agent.model_name)
    if model is None:
        model = Model(
            name=agent.model_name,
            provider=AURACALL_PROVIDER,
            type="language",
            credential=credential.id,
        )
    else:
        model.credential = credential.id
    await model.save()
    return model


async def register(
    agents: list[AuraCallAgent],
    default_agent_id: str,
    check_reachability: bool,
) -> dict[str, Any]:
    results: list[dict[str, Any]] = []
    registered_models: dict[str, Model] = {}

    for agent in agents:
        base_url, api_key = _agent_config(agent)
        reachable = (
            await _reachable(base_url, api_key, agent.model_name)
            if check_reachability
            else None
        )
        credential = await _ensure_credential(agent, base_url, api_key)
        model = await _ensure_model(agent, credential)
        registered_models[agent.id] = model
        results.append(
            {
                "agent_id": agent.id,
                "label": agent.label,
                "model": agent.model_name,
                "base_url": base_url,
                "reachable": reachable,
                "credential_id": credential.id,
                "model_id": model.id,
            }
        )

    default_model_id = None
    if default_agent_id:
        if default_agent_id not in registered_models:
            raise ValueError(
                f"Default agent {default_agent_id!r} is not one of: "
                f"{', '.join(sorted(registered_models))}"
            )
        default_model_id = registered_models[default_agent_id].id
        defaults = await DefaultModels.get_instance()
        defaults.default_chat_model = default_model_id
        defaults.default_transformation_model = default_model_id
        defaults.large_context_model = default_model_id
        defaults.default_tools_model = default_model_id
        await defaults.update()

    return {
        "registered": results,
        "default_language_model": default_model_id,
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--default-agent",
        default=os.environ.get(
            "OPEN_NOTEBOOK_AURACALL_DEFAULT_AGENT",
            "open-notebook-medium-chatgpt-soylei",
        ),
        help="AuraCall agent id to assign to all Open Notebook language defaults.",
    )
    parser.add_argument(
        "--skip-reachability",
        action="store_true",
        help="Register records without checking AuraCall /v1/models first.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    result = asyncio.run(
        register(
            agents=DEFAULT_AGENTS,
            default_agent_id=args.default_agent,
            check_reachability=not args.skip_reachability,
        )
    )
    print(json.dumps(result, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
